# Generated by Django 5.1.4 on 2025-06-02 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0005_alter_photo_options_alter_photofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.CreateModel(
            name='ManagerTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('max_assigned_users', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество исполнителей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Шаблон задачи менеджера',
                'verbose_name_plural': 'Шаблоны задач менеджера',
                'ordering': ['-created_at'],
            },
        ),
    ]
