# Generated by Django 5.1.4 on 2025-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager2', '0006_alter_tasktemplate_created_by_managertasktemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managertasktemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Шаблон задачи менеджера', 'verbose_name_plural': 'Шаблоны задач менеджеров'},
        ),
        migrations.AddField(
            model_name='managertasktemplate',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Доступно всем'),
        ),
        migrations.AlterField(
            model_name='managertasktemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='managertasktemplate',
            name='max_assigned_users',
            field=models.PositiveIntegerField(verbose_name='Максимальное количество исполнителей'),
        ),
    ]
